# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
---

include:
   - board: seeeduino_xiao_ble
     shield: licorice1_left
     cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    
   - board: seeeduino_xiao_ble
     shield: licorice1_right 
     cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
   
   - board: seeeduino_xiao_ble
     shield: settings_reset 

   - board: nice_nano_v2
     shield: licorice1_dongle dongle_display
     
   - board: nice_nano_v2
     shield: settings_reset
  
#

